### ISSUE TITLE
Error Writing Save to Disk

### ISSUE THREAD

**Issue by RugarPastrana** [JordanZeotni/BotW-Save-Manager#2]
Hi, I'm trying to convert a save from Wii U to Switch, and I cant save it.
I Attach my most recent log.
Greetings
[15-01-19-1.log](https://github.com/JordanZeotni/BotW-Save-Manager/files/2762093/15-01-19-1.log)

**Comment by DeltaJordan** [comment]
From what I can tell, your save converted in memory correctly but then failed to write to disk. On top of that, it looks like your log either failed to print the stacktrace of the error or just didn't due to the way I used the logging methods. 
I (hopefully) addressed the latter issue in the latest release, try to convert your save again with this version
https://github.com/JordanZeotni/BotW-Save-Manager/releases/tag/1.1.2

**Comment by RugarPastrana** [comment]
Hi, It failed again when trying to write to disk.

[16-01-19-1.log](https://github.com/JordanZeotni/BotW-Save-Manager/files/2765605/16-01-19-1.log)

**Comment by RugarPastrana** [comment]
This is the Save I want to convert, maybe you can check on it and tell me if something is wrong

https://drive.google.com/file/d/11UIeM8CtdybFkiQa_8rtwFkowcVtC1uC/view?usp=sharing

**Comment by DeltaJordan** [comment]
I didn't even notice when looking through your first log but there's for some reason a `game_data.sav` file in the root of your save folder that shouldn't be there normally.

![image](https://user-images.githubusercontent.com/11305269/51339199-750d7480-1a51-11e9-877e-7dbf18c44126.png)

Try deleting it and see if everything works once you try it on the Switch. 

In light of this, I'll be working on logging and error handling a bit more information for crashes to in turn allow the possibility of similar issues be resolved by users.

**Comment by RugarPastrana** [comment]
Welp,It works!

I don't know why that file was created, i used Saviine to rip my save from Wii U.

Anyway, I am using my old savestate on Switch, thank you so much!

**Comment by DeltaJordan** [comment]
Alright I'm glad we got that sorted out! Thanks a lot for your helpful reporting.
